import { createFileRoute, Link } from "@tanstack/react-router";
import { Mail, FileText, ListChecks, Search, MessageSquare, ArrowRight, Sparkles } from "lucide-react";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Aurora — AI Workplace Productivity Assistant" },
      { name: "description", content: "Automate emails, meeting notes, planning, research and chat with AI." },
    ],
  }),
  component: Dashboard,
});

const tools = [
  { to: "/email", title: "Smart Email Generator", desc: "Draft polished emails in seconds.", icon: Mail },
  { to: "/meetings", title: "Meeting Notes Summarizer", desc: "Turn raw notes into action-ready summaries.", icon: FileText },
  { to: "/tasks", title: "AI Task Planner", desc: "Break goals into prioritized task lists.", icon: ListChecks },
  { to: "/research", title: "AI Research Assistant", desc: "Get structured briefings on any topic.", icon: Search },
  { to: "/chat", title: "AI Chatbot", desc: "Conversational assistant for anything.", icon: MessageSquare },
];

function Dashboard() {
  return (
    <div className="mx-auto max-w-6xl p-6 md:p-10 space-y-10">
      <section className="rounded-2xl border border-border bg-card p-8 md:p-10 shadow-[var(--shadow-soft)] relative overflow-hidden">
        <div className="absolute -right-20 -top-20 h-64 w-64 rounded-full opacity-30 blur-3xl" style={{ background: "var(--gradient-primary)" }} />
        <div className="relative">
          <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-background/60 px-3 py-1 text-xs font-medium text-muted-foreground">
            <Sparkles className="h-3 w-3 text-primary" /> Powered by Lovable AI
          </span>
          <h1 className="mt-4 text-3xl md:text-4xl font-semibold tracking-tight text-foreground">
            Your workplace, supercharged.
          </h1>
          <p className="mt-3 max-w-xl text-muted-foreground">
            Five focused AI tools that take repetitive workplace tasks off your plate so you can spend time on what matters.
          </p>
        </div>
      </section>

      <section>
        <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground mb-4">Tools</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {tools.map((t) => {
            const Icon = t.icon;
            return (
              <Link
                key={t.to}
                to={t.to}
                className="group rounded-xl border border-border bg-card p-5 shadow-[var(--shadow-soft)] transition-all hover:-translate-y-0.5 hover:shadow-[var(--shadow-elevated)] hover:border-primary/40"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent text-accent-foreground mb-4">
                  <Icon className="h-5 w-5" />
                </div>
                <h3 className="font-semibold text-foreground">{t.title}</h3>
                <p className="mt-1 text-sm text-muted-foreground">{t.desc}</p>
                <span className="mt-4 inline-flex items-center text-sm font-medium text-primary">
                  Open <ArrowRight className="ml-1 h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
                </span>
              </Link>
            );
          })}
        </div>
      </section>

      <p className="text-xs text-muted-foreground">
        Responsible AI: Outputs are generated by AI and may contain errors. Review and edit before use.
      </p>
    </div>
  );
}
